auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: SimonShao
url: http://simon582.github.io
feed: /atom.xml
author_info: <a href="http://simon582.github.io/">SimonShao</a>
